-- AddColumn credentials to marketplace_connections
ALTER TABLE "marketplace_connections" ADD COLUMN IF NOT EXISTS "credentials" JSONB;

-- Extend MarketplaceType enum
ALTER TYPE "MarketplaceType" ADD VALUE IF NOT EXISTS 'SHOPIFY';
ALTER TYPE "MarketplaceType" ADD VALUE IF NOT EXISTS 'WOOCOMMERCE';
ALTER TYPE "MarketplaceType" ADD VALUE IF NOT EXISTS 'JUMPSELLER';
ALTER TYPE "MarketplaceType" ADD VALUE IF NOT EXISTS 'FALABELLA';
ALTER TYPE "MarketplaceType" ADD VALUE IF NOT EXISTS 'PARIS';
ALTER TYPE "MarketplaceType" ADD VALUE IF NOT EXISTS 'HITES';
ALTER TYPE "MarketplaceType" ADD VALUE IF NOT EXISTS 'RIPLEY';
ALTER TYPE "MarketplaceType" ADD VALUE IF NOT EXISTS 'WALMART';

-- Extend SaleChannel enum
ALTER TYPE "SaleChannel" ADD VALUE IF NOT EXISTS 'SHOPIFY';
ALTER TYPE "SaleChannel" ADD VALUE IF NOT EXISTS 'WOOCOMMERCE';
ALTER TYPE "SaleChannel" ADD VALUE IF NOT EXISTS 'JUMPSELLER';
ALTER TYPE "SaleChannel" ADD VALUE IF NOT EXISTS 'FALABELLA';
ALTER TYPE "SaleChannel" ADD VALUE IF NOT EXISTS 'PARIS';
ALTER TYPE "SaleChannel" ADD VALUE IF NOT EXISTS 'HITES';
ALTER TYPE "SaleChannel" ADD VALUE IF NOT EXISTS 'RIPLEY';
ALTER TYPE "SaleChannel" ADD VALUE IF NOT EXISTS 'WALMART';
